name: Pull Request Template Selector

on:
  pull_request:
    types: [opened, edited]

jobs:
  select-template:
    runs-on: ubuntu-latest
    steps:
      - name: Apply PR Template
        run: |
          if [[ "${{ github.event.pull_request.labels }}" == *"feature"* ]]; then
            echo "$(cat .github/PULL_REQUEST_TEMPLATE/feature_template.md)" > pr_body.md
          elif [[ "${{ github.event.pull_request.labels }}" == *"bugfix"* ]]; then
            echo "$(cat .github/PULL_REQUEST_TEMPLATE/bugfix_template.md)" > pr_body.md
          else
            echo "$(cat .github/PULL_REQUEST_TEMPLATE/default_template.md)" > pr_body.md
          fi
          
      - name: Update PR Description
        run: gh pr edit ${{ github.event.pull_request.number }} --body "$(cat pr_body.md)"
