name: Pull Request Template Selector

on:
  pull_request:
    types: [opened]

jobs:
  template-selector:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on Pull Request
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const templates = `
          ## Pull Request Templates

          Please select the appropriate template for your pull request:

          - [Bug Fix](.github/PULL_REQUEST_TEMPLATE/bug_fix.md)
          - [Feature Request](.github/PULL_REQUEST_TEMPLATE/feature_request.md)
          - [Documentation Update](.github/PULL_REQUEST_TEMPLATE/documentation_update.md)
          `;

          const issue_number = context.payload.pull_request.number;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: templates
          });
